name: Main Deploy
on:
  Push:
    branches:
    -main
jobs:
  extract-transform-load:
    runs-on: ubuntu-latest
    env: 
      PG_CONN_STRING: ${{ secrets.PG_CONN_STRING }}
      BITDOTIO_USER: SDahirSalman
      BITDOTIO_REPO: coviddata
     steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: python -m pip install --upgrade pip -r requirements.txt
      - name: ACS population by county
        run: |
             python venv/main.py \
             -local_source \
             -name acs_population_counties \
             venv/acs_5yr_population_data.csv \
             $BITDOTIO_USER/$BITDOTIO_REPO.population
      - name: NYT cases by county
        run: |
             python venv/main.py \
             -local_source \
             -name nyt_cases_counties \
             venv/trial.csv \
             $BITDOTIO_USER/$BITDOTIO_REPO.covidcases
      - name: CDC vaccines by county
      - name: Create CA report table
        run: |
             python /venv/sql_executor.py \
             venv/ca_covid_data.sql \
             $BITDOTIO_USER \
             $BITDOTIO_REPO




