name: Main Deploy
on: 
  push: 
    branches:
    - main
jobs:
  extract-transform-load:
    runs-on: ubuntu-latest
    env: 
      PG_CONN_STRING: postgresql://SDahirSalman_demo_db_connection:37UmC_mvRKMxTiPFpszmANYZrDNkT@db.bit.io
      BITDOTIO_USER: SDahirSalman
      BITDOTIO_REPO: coviddata
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.1'
      - name: Install dependencies
        run: python -m pip install --upgrade pip -r venv/requirements.txt
      - name: Stackoverflow Post Questions
        run: |
             python venv/main.py \
             -big_query \
             -name from_big_query \
             {stackoverflow posts questions url} \
             $BITDOTIO_USER/$BITDOTIO_REPO.posts_questions
      - name: Stackoverflow Posts Answers 
        run: |
             python venv/main.py \
             -big_query \
             -name from_big_query \
             {stackoverflow answers url} \
             $BITDOTIO_USER/$BITDOTIO_REPO.posts_answers 
      - name: Number of Questions Answered by Users related to BigQuery Topic
        run: |
             python venv/users_answer.py \
             venv/ca_covid_data.sql \
             $BITDOTIO_USER \
             $BITDOTIO_REPO
